name: Simple Workflow
on:  
  push:
    branches: dev

jobs:
  # Job 1: Create PR to main branch
    create-PR-to-main: 
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:  
            ref: 'dev'

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: 'dev-auto-pr' # source branch for pr
            base: 'main' # target branch for pr
            commit-message: Update from Dev Environment
            title: 'Update from Dev Environment'
            body: Automatic pull request creation from Dev to Main after successful deployment.
            labels: automated pr