name: Simple Workflow
on:  
  push:
    branches: dev

# Job 5: Create PR to main branch
create-PR-to-main: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
        base: main
        commit-message: Update from Dev Environment
        title: 'Update from Dev Environment'
        body: Automatic pull request creation from Dev to Main after successful deployment.
        labels: automated pr